/* SPDX-License-Identifier: MIT OR Apache-2.0 */
/* Generated by cbindgen from rust/src. Do not edit. */

#ifndef LASRS_H
#define LASRS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Bumped on every incompatible change of the C ABI.
 */
#define LASRS_ABI_VERSION 1

typedef enum LasrsStatus {
  LASRS_STATUS_OK = 0,
  LASRS_STATUS_ERROR = 1,
  LASRS_STATUS_PANIC = 2,
} LasrsStatus;

/**
 * Origin of a seek, as in `std::io::SeekFrom`.
 */
typedef enum LasrsSeekOrigin {
  LASRS_SEEK_ORIGIN_START = 0,
  LASRS_SEEK_ORIGIN_CURRENT = 1,
  LASRS_SEEK_ORIGIN_END = 2,
} LasrsSeekOrigin;

typedef enum LasrsLodSelectionKind {
  LASRS_LOD_SELECTION_KIND_ALL = 0,
  LASRS_LOD_SELECTION_KIND_RESOLUTION = 1,
  LASRS_LOD_SELECTION_KIND_LEVEL = 2,
  LASRS_LOD_SELECTION_KIND_LEVEL_MIN_MAX = 3,
} LasrsLodSelectionKind;

typedef enum LasrsLazParallelism {
  LASRS_LAZ_PARALLELISM_YES = 0,
  LASRS_LAZ_PARALLELISM_NO = 1,
} LasrsLazParallelism;

typedef struct LasrsBuilder LasrsBuilder;

typedef struct LasrsCopcReader LasrsCopcReader;

/**
 * Opaque handle; points at a `las::Header`.
 */
typedef struct LasrsHeader LasrsHeader;

typedef struct LasrsPointData LasrsPointData;

typedef struct LasrsReader LasrsReader;

typedef struct LasrsWriter LasrsWriter;

typedef struct LasrsVersion {
  uint8_t major;
  uint8_t minor;
} LasrsVersion;

typedef struct LasrsDate {
  int32_t year;
  uint32_t month;
  uint32_t day;
} LasrsDate;

/**
 * Borrowed UTF-8 string, not NUL-terminated.
 */
typedef struct LasrsStr {
  const uint8_t *ptr;
  size_t len;
} LasrsStr;

/**
 * Borrowed byte slice.
 */
typedef struct LasrsBytes {
  const uint8_t *ptr;
  size_t len;
} LasrsBytes;

typedef struct LasrsFormat {
  bool has_gps_time;
  bool has_color;
  bool is_extended;
  bool has_waveform;
  bool has_nir;
  uint16_t extra_bytes;
  bool is_compressed;
} LasrsFormat;

typedef struct LasrsTransform {
  double scale;
  double offset;
} LasrsTransform;

typedef struct LasrsTransforms {
  struct LasrsTransform x;
  struct LasrsTransform y;
  struct LasrsTransform z;
} LasrsTransforms;

/**
 * All scalar and byte fields of a [`Builder`]; VLRs are passed separately.
 */
typedef struct LasrsBuilderFields {
  bool has_date;
  struct LasrsDate date;
  uint16_t file_source_id;
  struct LasrsStr generating_software;
  uint8_t gps_time_type;
  uint8_t guid[16];
  bool has_synthetic_return_numbers;
  bool has_wkt_crs;
  struct LasrsBytes padding;
  struct LasrsFormat point_format;
  struct LasrsBytes point_padding;
  struct LasrsStr system_identifier;
  struct LasrsTransforms transforms;
  struct LasrsVersion version;
  struct LasrsBytes vlr_padding;
} LasrsBuilderFields;

/**
 * Borrowed view of a [`Vlr`].
 */
typedef struct LasrsVlr {
  struct LasrsStr user_id;
  uint16_t record_id;
  struct LasrsStr description;
  struct LasrsBytes data;
} LasrsVlr;

/**
 * Reads up to `len` bytes into `buf`, storing the count in `read`.
 * Returns false on error. Must not throw or unwind.
 */
typedef bool (*LasrsReadFn)(void *context, uint8_t *buf, size_t len, size_t *read);

/**
 * Seeks and stores the new absolute position in `position`.
 */
typedef bool (*LasrsSeekFn)(void *context,
                            int64_t offset,
                            enum LasrsSeekOrigin origin,
                            uint64_t *position);

/**
 * A caller-implemented input stream. `context` must outlive every handle
 * created from it and must not be used concurrently.
 */
typedef struct LasrsInputStream {
  void *context;
  LasrsReadFn read;
  LasrsSeekFn seek;
} LasrsInputStream;

typedef struct LasrsVoxelKey {
  int32_t l;
  int32_t x;
  int32_t y;
  int32_t z;
} LasrsVoxelKey;

typedef struct LasrsEntry {
  struct LasrsVoxelKey key;
  uint64_t offset;
  int32_t byte_size;
  int32_t point_count;
} LasrsEntry;

/**
 * Only the fields used by `kind` are read.
 */
typedef struct LasrsLodSelection {
  enum LasrsLodSelectionKind kind;
  double resolution;
  int32_t level;
  int32_t level_max;
} LasrsLodSelection;

typedef struct LasrsVector {
  double x;
  double y;
  double z;
} LasrsVector;

typedef struct LasrsBounds {
  struct LasrsVector min;
  struct LasrsVector max;
} LasrsBounds;

/**
 * `bounds` is only read when `within` is true.
 */
typedef struct LasrsBoundsSelection {
  bool within;
  struct LasrsBounds bounds;
} LasrsBoundsSelection;

typedef struct LasrsColor {
  uint16_t red;
  uint16_t green;
  uint16_t blue;
} LasrsColor;

typedef struct LasrsWaveform {
  uint8_t wave_packet_descriptor_index;
  uint64_t byte_offset_to_waveform_data;
  uint32_t waveform_packet_size_in_bytes;
  float return_point_waveform_location;
  float x_t;
  float y_t;
  float z_t;
} LasrsWaveform;

/**
 * A point; `extra_bytes` travel in a separate contiguous buffer, in point
 * order, `extra_bytes_len` bytes per point.
 */
typedef struct LasrsPoint {
  double x;
  double y;
  double z;
  uint16_t intensity;
  uint8_t return_number;
  uint8_t number_of_returns;
  /**
   * 0 = RightToLeft, 1 = LeftToRight
   */
  uint8_t scan_direction;
  bool is_edge_of_flight_line;
  uint8_t classification;
  bool is_synthetic;
  bool is_key_point;
  bool is_withheld;
  bool is_overlap;
  uint8_t scanner_channel;
  float scan_angle;
  uint8_t user_data;
  uint16_t point_source_id;
  bool has_gps_time;
  double gps_time;
  bool has_color;
  struct LasrsColor color;
  bool has_waveform;
  struct LasrsWaveform waveform;
  bool has_nir;
  uint16_t nir;
  size_t extra_bytes_len;
} LasrsPoint;

typedef struct LasrsCopcInfoVlr {
  double center_x;
  double center_y;
  double center_z;
  double halfsize;
  double spacing;
  double gpstime_minimum;
  double gpstime_maximum;
} LasrsCopcInfoVlr;

/**
 * Writes all `len` bytes of `buf`. Returns false on error.
 */
typedef bool (*LasrsWriteFn)(void *context, const uint8_t *buf, size_t len);

/**
 * Flushes buffered output. Returns false on error.
 */
typedef bool (*LasrsFlushFn)(void *context);

/**
 * A caller-implemented output stream, same rules as [`LasrsInputStream`].
 */
typedef struct LasrsOutputStream {
  void *context;
  LasrsWriteFn write;
  LasrsSeekFn seek;
  LasrsFlushFn flush;
} LasrsOutputStream;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t lasrs_abi_version(void);

struct LasrsBuilder *lasrs_builder_from_version(struct LasrsVersion version);

struct LasrsBuilder *lasrs_builder_from_header(const struct LasrsHeader *header);

void lasrs_builder_free(struct LasrsBuilder *builder);

/**
 * Borrowed view, valid until the builder is freed.
 */
struct LasrsBuilderFields lasrs_builder_fields(const struct LasrsBuilder *builder);

size_t lasrs_builder_vlrs_len(const struct LasrsBuilder *builder);

struct LasrsVlr lasrs_builder_vlr(const struct LasrsBuilder *builder, size_t index);

size_t lasrs_builder_evlrs_len(const struct LasrsBuilder *builder);

struct LasrsVlr lasrs_builder_evlr(const struct LasrsBuilder *builder, size_t index);

enum LasrsStatus lasrs_builder_into_header(const struct LasrsBuilder *base,
                                           const struct LasrsBuilderFields *fields,
                                           const struct LasrsVlr *vlrs,
                                           size_t n_vlrs,
                                           const struct LasrsVlr *evlrs,
                                           size_t n_evlrs,
                                           struct LasrsHeader **out);

/**
 * Writes `has_version = false` if no version supports the configuration.
 */
enum LasrsStatus lasrs_builder_minimum_supported_version(const struct LasrsBuilder *base,
                                                         const struct LasrsBuilderFields *fields,
                                                         const struct LasrsVlr *vlrs,
                                                         size_t n_vlrs,
                                                         const struct LasrsVlr *evlrs,
                                                         size_t n_evlrs,
                                                         bool *has_version,
                                                         struct LasrsVersion *out);

enum LasrsStatus lasrs_copc_reader_from_path(struct LasrsStr path, struct LasrsCopcReader **out);

enum LasrsStatus lasrs_copc_reader_new(struct LasrsInputStream stream,
                                       struct LasrsCopcReader **out);

void lasrs_copc_reader_free(struct LasrsCopcReader *reader);

/**
 * Borrowed, valid while the reader is alive.
 */
const struct LasrsHeader *lasrs_copc_reader_header(const struct LasrsCopcReader *reader);

size_t lasrs_copc_reader_hierarchy_entries_len(const struct LasrsCopcReader *reader);

/**
 * Writes up to `capacity` entries to `out`; returns the number written.
 */
size_t lasrs_copc_reader_hierarchy_entries(const struct LasrsCopcReader *reader,
                                           struct LasrsEntry *out,
                                           size_t capacity);

/**
 * Returns false if there is no entry for `key`.
 */
bool lasrs_copc_reader_hierarchy_entry(const struct LasrsCopcReader *reader,
                                       struct LasrsVoxelKey key,
                                       struct LasrsEntry *out);

enum LasrsStatus lasrs_copc_reader_read_entry(struct LasrsCopcReader *reader,
                                              struct LasrsEntry entry,
                                              struct LasrsPointData **out);

enum LasrsStatus lasrs_copc_reader_query(struct LasrsCopcReader *reader,
                                         struct LasrsLodSelection levels,
                                         struct LasrsBoundsSelection bounds,
                                         struct LasrsPointData **out);

/**
 * Message of the last failed call on this thread. Valid until the next
 * failing call on the same thread.
 */
struct LasrsStr lasrs_last_error(void);

struct LasrsHeader *lasrs_header_default(void);

struct LasrsHeader *lasrs_header_from_version(struct LasrsVersion version);

struct LasrsHeader *lasrs_header_clone(const struct LasrsHeader *header);

void lasrs_header_free(struct LasrsHeader *header);

bool lasrs_header_eq(const struct LasrsHeader *a, const struct LasrsHeader *b);

uint16_t lasrs_header_file_source_id(const struct LasrsHeader *header);

uint8_t lasrs_header_gps_time_type(const struct LasrsHeader *header);

bool lasrs_header_has_synthetic_return_numbers(const struct LasrsHeader *header);

bool lasrs_header_has_wkt_crs(const struct LasrsHeader *header);

void lasrs_header_guid(const struct LasrsHeader *header, uint8_t (*out)[16]);

struct LasrsVersion lasrs_header_version(const struct LasrsHeader *header);

struct LasrsStr lasrs_header_system_identifier(const struct LasrsHeader *header);

struct LasrsStr lasrs_header_generating_software(const struct LasrsHeader *header);

/**
 * Returns false if the header has no date.
 */
bool lasrs_header_date(const struct LasrsHeader *header, struct LasrsDate *out);

struct LasrsBytes lasrs_header_padding(const struct LasrsHeader *header);

struct LasrsFormat lasrs_header_point_format(const struct LasrsHeader *header);

struct LasrsTransforms lasrs_header_transforms(const struct LasrsHeader *header);

struct LasrsBounds lasrs_header_bounds(const struct LasrsHeader *header);

uint64_t lasrs_header_number_of_points(const struct LasrsHeader *header);

/**
 * Returns false if `n` is not a valid return number for this header.
 */
bool lasrs_header_number_of_points_by_return(const struct LasrsHeader *header,
                                             uint8_t n,
                                             uint64_t *out);

struct LasrsBytes lasrs_header_vlr_padding(const struct LasrsHeader *header);

struct LasrsBytes lasrs_header_point_padding(const struct LasrsHeader *header);

size_t lasrs_header_vlrs_len(const struct LasrsHeader *header);

/**
 * Borrowed view, valid until the header is modified or freed.
 */
struct LasrsVlr lasrs_header_vlr(const struct LasrsHeader *header, size_t index);

size_t lasrs_header_evlrs_len(const struct LasrsHeader *header);

/**
 * Borrowed view, valid until the header is modified or freed.
 */
struct LasrsVlr lasrs_header_evlr(const struct LasrsHeader *header, size_t index);

bool lasrs_header_has_crs_vlrs(const struct LasrsHeader *header);

void lasrs_header_clear(struct LasrsHeader *header);

enum LasrsStatus lasrs_header_add_point(struct LasrsHeader *header,
                                        const struct LasrsPoint *point,
                                        const uint8_t *extra_bytes);

void lasrs_header_add_point_data(struct LasrsHeader *header, const struct LasrsPointData *points);

void lasrs_header_remove_crs_vlrs(struct LasrsHeader *header);

enum LasrsStatus lasrs_header_set_wkt_crs(struct LasrsHeader *header,
                                          struct LasrsBytes wkt_crs_bytes);

/**
 * Returns false if the header has no WKT CRS. The bytes are borrowed.
 */
bool lasrs_header_get_wkt_crs_bytes(const struct LasrsHeader *header, struct LasrsBytes *out);

/**
 * Returns false if the header has no COPC info VLR.
 */
bool lasrs_header_copc_info_vlr(const struct LasrsHeader *header, struct LasrsCopcInfoVlr *out);

struct LasrsPointData *lasrs_point_data_build(struct LasrsFormat format,
                                              struct LasrsTransforms transforms);

enum LasrsStatus lasrs_point_data_build_from_bytes(struct LasrsFormat format,
                                                   struct LasrsTransforms transforms,
                                                   struct LasrsBytes bytes,
                                                   struct LasrsPointData **out);

enum LasrsStatus lasrs_point_data_build_from_points(struct LasrsFormat format,
                                                    struct LasrsTransforms transforms,
                                                    const struct LasrsPoint *points,
                                                    size_t n,
                                                    const uint8_t *extra_bytes,
                                                    struct LasrsPointData **out);

struct LasrsPointData *lasrs_point_data_clone(const struct LasrsPointData *points);

void lasrs_point_data_free(struct LasrsPointData *points);

size_t lasrs_point_data_len(const struct LasrsPointData *points);

struct LasrsFormat lasrs_point_data_format(const struct LasrsPointData *points);

struct LasrsTransforms lasrs_point_data_transforms(const struct LasrsPointData *points);

/**
 * Borrowed, valid until the point data is modified or freed.
 */
struct LasrsBytes lasrs_point_data_raw_bytes(const struct LasrsPointData *points);

size_t lasrs_point_data_record_len(const struct LasrsPointData *points);

/**
 * Resizes to `n` points; returns the writable byte slab
 * (`n * record_len` bytes), valid until the next modification.
 */
uint8_t *lasrs_point_data_resize_for(struct LasrsPointData *points, size_t n);

/**
 * Decodes all points. `out` holds `len()` points and `extra_bytes_out`
 * holds `len() * format.extra_bytes` bytes.
 */
enum LasrsStatus lasrs_point_data_points(const struct LasrsPointData *points,
                                         struct LasrsPoint *out,
                                         uint8_t *extra_bytes_out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_x_raw(const struct LasrsPointData *points, int32_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_y_raw(const struct LasrsPointData *points, int32_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_z_raw(const struct LasrsPointData *points, int32_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_x(const struct LasrsPointData *points, double *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_y(const struct LasrsPointData *points, double *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_z(const struct LasrsPointData *points, double *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_intensity(const struct LasrsPointData *points, uint16_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_classification(const struct LasrsPointData *points, uint8_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_return_number(const struct LasrsPointData *points, uint8_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_number_of_returns(const struct LasrsPointData *points, uint8_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_scan_angle_degrees(const struct LasrsPointData *points, float *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_user_data(const struct LasrsPointData *points, uint8_t *out);

/**
 * Writes `len()` values to `out`.
 */
void lasrs_point_data_point_source_id(const struct LasrsPointData *points, uint16_t *out);

/**
 * Returns false (and writes nothing) if the format has no GPS time.
 */
bool lasrs_point_data_gps_time(const struct LasrsPointData *points, double *out);

/**
 * Returns false (and writes nothing) if the format has no color.
 */
bool lasrs_point_data_rgb(const struct LasrsPointData *points, struct LasrsColor *out);

/**
 * Returns false (and writes nothing) if the format has no NIR.
 */
bool lasrs_point_data_nir(const struct LasrsPointData *points, uint16_t *out);

enum LasrsStatus lasrs_reader_from_path(struct LasrsStr path, struct LasrsReader **out);

enum LasrsStatus lasrs_reader_new(struct LasrsInputStream stream, struct LasrsReader **out);

enum LasrsStatus lasrs_reader_with_options(struct LasrsInputStream stream,
                                           enum LasrsLazParallelism laz_parallelism,
                                           struct LasrsReader **out);

void lasrs_reader_free(struct LasrsReader *reader);

/**
 * Borrowed, valid while the reader is alive.
 */
const struct LasrsHeader *lasrs_reader_header(const struct LasrsReader *reader);

enum LasrsStatus lasrs_reader_read_points(struct LasrsReader *reader,
                                          uint64_t n,
                                          struct LasrsPointData **out);

enum LasrsStatus lasrs_reader_read_all(struct LasrsReader *reader, struct LasrsPointData **out);

enum LasrsStatus lasrs_reader_fill_points(struct LasrsReader *reader,
                                          uint64_t n,
                                          struct LasrsPointData *target,
                                          uint64_t *read);

enum LasrsStatus lasrs_reader_seek(struct LasrsReader *reader, uint64_t position);

enum LasrsStatus lasrs_format_new(uint8_t n, struct LasrsFormat *out);

uint16_t lasrs_format_len(struct LasrsFormat format);

enum LasrsStatus lasrs_format_to_u8(struct LasrsFormat format, uint8_t *out);

enum LasrsStatus lasrs_transform_inverse(struct LasrsTransform transform, double n, int32_t *out);

enum LasrsStatus lasrs_bounds_adapt(struct LasrsBounds bounds,
                                    struct LasrsTransforms transforms,
                                    struct LasrsBounds *out);

enum LasrsStatus lasrs_writer_from_path(struct LasrsStr path,
                                        const struct LasrsHeader *header,
                                        struct LasrsWriter **out);

enum LasrsStatus lasrs_writer_new(struct LasrsOutputStream stream,
                                  const struct LasrsHeader *header,
                                  struct LasrsWriter **out);

enum LasrsStatus lasrs_writer_with_options(struct LasrsOutputStream stream,
                                           const struct LasrsHeader *header,
                                           enum LasrsLazParallelism laz_parallelism,
                                           struct LasrsWriter **out);

/**
 * Closes the writer if still open. Errors while closing are reported
 * through the status, the handle is freed either way.
 */
enum LasrsStatus lasrs_writer_free(struct LasrsWriter *writer);

enum LasrsStatus lasrs_writer_close(struct LasrsWriter *writer);

/**
 * Returns a new owned copy of the writer's current header.
 */
struct LasrsHeader *lasrs_writer_header(struct LasrsWriter *writer);

enum LasrsStatus lasrs_writer_write_point(struct LasrsWriter *writer,
                                          const struct LasrsPoint *point,
                                          const uint8_t *extra_bytes);

enum LasrsStatus lasrs_writer_write_points(struct LasrsWriter *writer,
                                           const struct LasrsPointData *points);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LASRS_H */
